//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woohoo.ChecksumCalculator.AvaloniaDesktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woohoo.ChecksumCalculator.AvaloniaDesktop.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Calculator.
        /// </summary>
        public static string AboutWindow_Caption {
            get {
                return ResourceManager.GetString("AboutWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.0 - Copyright 2022 Hugues Valois.
        /// </summary>
        public static string AboutWindow_Description {
            get {
                return ResourceManager.GetString("AboutWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithms.
        /// </summary>
        public static string Algorithms {
            get {
                return ResourceManager.GetString("Algorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File(s).
        /// </summary>
        public static string BrowseDialogTitle {
            get {
                return ResourceManager.GetString("BrowseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC32.
        /// </summary>
        public static string ChecksumCRC32 {
            get {
                return ResourceManager.GetString("ChecksumCRC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5.
        /// </summary>
        public static string ChecksumMD5 {
            get {
                return ResourceManager.GetString("ChecksumMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        public static string ChecksumSHA1 {
            get {
                return ResourceManager.GetString("ChecksumSHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256.
        /// </summary>
        public static string ChecksumSHA256 {
            get {
                return ResourceManager.GetString("ChecksumSHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA384.
        /// </summary>
        public static string ChecksumSHA384 {
            get {
                return ResourceManager.GetString("ChecksumSHA384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA512.
        /// </summary>
        public static string ChecksumSHA512 {
            get {
                return ResourceManager.GetString("ChecksumSHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify file path to an existing file..
        /// </summary>
        public static string ErrorNoFileSpecified {
            get {
                return ResourceManager.GetString("ErrorNoFileSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_bout....
        /// </summary>
        public static string MainWindow_AboutButton {
            get {
                return ResourceManager.GetString("MainWindow_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string MainWindow_BrowseButton {
            get {
                return ResourceManager.GetString("MainWindow_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_alculate.
        /// </summary>
        public static string MainWindow_CalculateButton {
            get {
                return ResourceManager.GetString("MainWindow_CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string MainWindow_CancelButton {
            get {
                return ResourceManager.GetString("MainWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Calculator.
        /// </summary>
        public static string MainWindow_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lear.
        /// </summary>
        public static string MainWindow_ClearButton {
            get {
                return ResourceManager.GetString("MainWindow_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string MainWindow_PathLabel {
            get {
                return ResourceManager.GetString("MainWindow_PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Calculator.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string ResultChecksum {
            get {
                return ResourceManager.GetString("ResultChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        public static string ResultFile {
            get {
                return ResourceManager.GetString("ResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0}.
        /// </summary>
        public static string ResultSize {
            get {
                return ResourceManager.GetString("ResultSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1} secs].
        /// </summary>
        public static string ResultTime {
            get {
                return ResourceManager.GetString("ResultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File(s) ....
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
    }
}
